config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get 'contact', to: "pages#contact", as: 'contact'

  resources :users, only: [:index, :new, :create, :destroy]


  resources :cours do
    get 'download', to: "cours#download"
    get 'download_aditional_file/:file', to: "cours#download_aditional_file", as: 'download_aditional_file'
  end



  resources :cours_users, only: [:index, :new]

  # API routing
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cours, only: [ :index ]
      resources :users, only: [ :index ]
      resources :cours_users, only: [ :index, :create, :destroy ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cour.rb
class Cour < ApplicationRecord

  has_many :cours_users, dependent: :destroy
  has_many :users, through: :cours_users

  # Carrierwave
  mount_uploader :file, FileUploader
  mount_uploader :img, ImgUploader
  mount_uploaders :aditional_files, AdditionalFilesUploader

  validates :img, presence: true

  @categories = ["Histoire", "Géographie", "EMC"]
  validates :category, presence: true, inclusion: { in: @categories }

  @levels = ["6ème", "5ème", "4ème", "3ème", "2nd", "1ère", "Terminale", "All"]
  validates :level, presence: true, inclusion: { in: @levels }

  validates :name, presence: true
end

app/models/cours_user.rb
class CoursUser < ApplicationRecord
  belongs_to :user
  belongs_to :cour
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :cours_users, dependent: :destroy
  has_many :cours, through: :cours_users

  validates :username, presence: true, uniqueness: true

  @status = ["Admin", "Prof", "Elève"]
  validates :status, presence: true, inclusion: { in: @status }

  @levels = ["6ème", "5ème", "4ème", "3ème", "2nd", "1ère", "Terminale", "All"]
  validates :level, presence: true, inclusion: { in: @levels }
end

app/controllers/api/v1/cours_controller.rb
class Api::V1::CoursController < ActionController::Base
  def index
    @cours = Cour.all
    render json: @cours
  end
end

app/controllers/api/v1/cours_users_controller.rb
class Api::V1::CoursUsersController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def index
    @cours = CoursUser.all
    render json: @cours
  end

  def create
    cours_user = CoursUser.new(cours_user_params)
    cours_user.save
    render json: cours_user
  end

  def destroy
    cours_user = CoursUser.find(params[:id])
    cours_user.destroy
    render json: cours_user
  end

  private

  def cours_user_params
    params.permit(:user_id, :cour_id)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::Base
  def index
    @users = User.where(status: 'Elève')
    render json: @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  after_action :verify_authorized, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :status])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  def index
    @hist_cours = Cour.where(category: "Histoire").sort_by { |cours| cours.name }
    @level_hist = []
    @hist_cours.each do |cours|
      if !@level_hist.include?(cours.level)
        @level_hist << cours.level
      end
    end
    @geo_cours = Cour.where(category: "Géographie").sort_by { |cours| cours.name }
    @level_geo = []
    @geo_cours.each do |cours_geo|
      if !@level_geo.include?(cours_geo.level)
        @level_geo << cours_geo.level
      end
    end
    @emc_cours = Cour.where(category: "EMC").sort_by { |cours| cours.name }
    @level_emc = []
    @emc_cours.each do |cours_emc|
      if !@level_emc.include?(cours_emc.level)
        @level_emc << cours_emc.level
      end
    end
    authorize(:cour)
  end

  def show
    @cours = Cour.find(params[:id])
    authorize @cours
  end

  def new
    @cours = Cour.new
    authorize @cours
  end

  def create
    @cours = Cour.new(cours_params)
    authorize @cours
    if @cours.save
     redirect_to cours_path
    else
      render :new
    end
  end

  def edit
    @cours = Cour.find(params[:id])
    authorize @cours
  end

  def update
    @cours = Cour.find(params[:id])
    authorize @cours
    if @cours.update(cours_params)
      redirect_to cour_path(@cours)
    else
      render :edit
    end
  end

  def destroy
    @cours = Cour.find(params[:id])
    authorize @cours
    @cours.destroy
    redirect_to cours_path
  end

  def download
    file = Cour.find(params[:cour_id]).file
    data = open(file.url)
    send_data data.read, type: data.content_type, x_sendfile: true
    authorize(:cour)
  end

  def download_aditional_file
    cour = Cour.find(params[:cour_id]).aditional_files
    file_identifier = params[:file] + "." + params[:format]
    aws_file = ""
    cour.each do |file|
      if file.identifier === file_identifier
        aws_file = file
      end
    end
    data = open(aws_file.url)
    send_data data.read, type: data.content_type, x_sendfile: true
    authorize(:cour)
  end

  private

  def cours_params
    params.require(:cour).permit(:name, :description, :category, :level, :file, :img, {aditional_files: []})
  end
end

app/controllers/cours_users_controller.rb
class CoursUsersController < ApplicationController
  def index
    cours = current_user.cours
    @hit_cours = cours.where(category: "Histoire").sort_by { |cours| cours.name }.reverse
    @geo_cours = cours.where(category: "Géographie").sort_by { |cours| cours.name }.reverse
    @emc_cours = cours.where(category: "EMC").sort_by { |cours| cours.name }.reverse
    authorize(:cour_user)
  end

  def new
    @users = User.where(status: 'Elève')
    @cours_user = CoursUser.new
    authorize(:cour_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact]

  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    else
      if current_user.status === 'Elève'
        redirect_to cours_users_path
      else
        redirect_to cours_path
      end
    end
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
     redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :status, :level, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cours/edit.html.erb
<div class="container">
  <h1 class="title-tab">Mise à jour de cours</h1>
  <div class="form-new-cours">
    <%= simple_form_for @cours do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :category, label:"Matière", collection: ["Histoire", "Géographie", "EMC"] %>
        <%= f.input :name, label:"Titre", required: true %>
        <%= f.input :level, label:"Niveau", collection: ["6ème", "5ème", "4ème", "3ème", "2nd", "1ère", "Terminale", "All"], required: true %>
        <%= f.input :file, label:"Cours", as: :file %>
        <%= f.input :img, label:"Image", as: :file %>
        <%= f.label "Fichiers supplémentaires : "  %>
        <%= f.file_field :aditional_files, multiple: :true %>

        <%= f.input :description, as: :text, label:"Informations" %>
        <p class="info-link">*Pour ajouter un lien copier cette balise et remplacez les majuscules : &#60;a href="LIEN">TEXT DU LIEN&#60;/a></p>
      </div>

      <div class="form-actions">
        <div class="btn-center">
          <%= f.button :submit, "Mettre à jour" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cours/index.html.erb
<div class="container">
  <div class="tab d-flex">
    <button class="tablinks histoire">Histoire</button>
    <button class="tablinks geo">Géographie</button>
    <button class="tablinks emc">EMC</button>
  </div>

  <div class="all-cours">
    <div id="Histoire" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">Histoire</h2>

      <% if !@hist_cours.empty? %>

        <div class="accordion" id="accordionHIST">
          <% @level_hist.each do |level| %>
            <div class="card">

              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-HIST-<%= level %>" aria-expanded="false" aria-controls="collapse-HIST-<%= level %>">
                <div class="card-header" id="headingOne">
                  <h4 class="mb-0">
                    <%= level %>
                  </h4>
                </div>
              </button>

              <div id="collapse-HIST-<%= level %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordionHIST">
                <div class="card-body">
                    <% @hist_cours.each do |c| %>
                      <% if c.level === level %>
                        <%= link_to cour_path(c.id), class:'cours-link' do %>

                            <div class="card-product">
                              <img src="<%= c.img %>" />
                              <div class="card-product-infos">
                                <h2><%= c.name %></h2>
                              </div>
                            </div>

                        <% end %>
                      <% end %>
                    <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      <% else %>
        <p>Pas de cours d'histoire pour le moment !</p>
      <% end %>
    </div>


    <div id="Géographie" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">Géographie</h2>

      <% if !@geo_cours.empty? %>

        <div class="accordion" id="accordionGEO">
          <% @level_geo.each do |level| %>
            <div class="card">

              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-GEO-<%= level %>" aria-expanded="false" aria-controls="collapse-GEO-<%= level %>">
                <div class="card-header" id="headingTwo">
                  <h4 class="mb-0">
                    <%= level %>
                  </h4>
                </div>
              </button>

              <div id="collapse-GEO-<%= level %>" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionGEO">
                <div class="card-body">
                  <% @geo_cours.each do |c| %>
                    <% if c.level === level %>
                      <%= link_to cour_path(c.id), class:'cours-link' do %>
                        <div class="card-product">
                          <img src="<%= c.img %>" />
                          <div class="card-product-infos">
                            <h2><%= c.name %></h2>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      <% else %>
        <p>Pas de cours de géographie pour le moment !</p>
      <% end %>
    </div>


    <div id="EMC" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">EMC</h2>
      <% if !@emc_cours.empty? %>


        <div class="accordion" id="accordionEMC">
          <% @level_emc.each do |level| %>
            <div class="card">

              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-EMC-<%= level %>" aria-expanded="false" aria-controls="collapse-EMC-<%= level %>">
                <div class="card-header" id="headingThree">
                  <h4 class="mb-0">
                    <%= level %>
                  </h4>
                </div>
              </button>

              <div id="collapse-EMC-<%= level %>" class="collapse" aria-labelledby="headingThree" data-parent="#accordionEMC">
                <div class="card-body">
                  <% @emc_cours.each do |c| %>
                    <% if c.level === level %>
                      <%= link_to cour_path(c.id), class:'cours-link' do %>
                        <div class="card-product">
                          <img src="<%= c.img %>" />
                          <div class="card-product-infos">
                            <h2><%= c.name %></h2>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>


      <% else %>
        <p>Pas de cours d'EMC pour le moment !</p>
      <% end %>
    </div>
  </div>

  <% if current_user.status === "Admin" %>
    <div class="btn-center">
      <%= button_to "Créer un cours", new_cour_path, method: :get, class: "btn" %>
    </div>
  <% end %>

</div>

app/views/cours/new.html.erb
<div class="container">
  <h1 class="title-tab">Création de cours</h1>
  <div class="form-new-cours">
    <%= simple_form_for @cours do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :category, label:"Matière", collection: ["Histoire", "Géographie", "EMC"] %>
        <%= f.input :name, label:"Titre", required: true %>
        <%= f.input :level, label:"Niveau", collection: ["6ème", "5ème", "4ème", "3ème", "2nd", "1ère", "Terminale", "All"], required: true %>
        <%= f.input :file, label:"Cours", as: :file %>
        <%= f.input :img, label:"Image", as: :file %>
        <%= f.label "Fichiers supplémentaires : "  %>
        <%= f.file_field :aditional_files, multiple: :true %>

        <%= f.input :description, as: :text, label:"Informations" %>
        <p class="info-link">*Pour ajouter un lien copier cette balise et remplacez les majuscules : &#60;a href="LIEN">TEXT DU LIEN&#60;/a></p>
      </div>

      <div class="form-actions">
        <div class="btn-center">
          <%= f.button :submit, "Créer" %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/cours/show.html.erb
  <!-- MODAL DELETE -->
      <div id="modal-delete" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="exampleModalLongTitle">Supprimer le cours ?</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Voulez vous vraiment supprimer ce cours ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <%= button_to cour_path(params[:id]), method: :delete, class:"btn btn-danger" do %>
                Supprimer
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <!-- MODAL DELET FINISH -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @cours.img %>);">
  <div class="container">
    <h1><%= @cours.name %></h1>
  </div>
</div>

<div class="container">
  <h5 class="matiere"><%= @cours.category %> / <%= @cours.level %></h5>

  <% if @cours.file.file != nil %>
    <div class="bloc-cours download">
      <h3>Cours :</h3>
      <%= link_to cour_download_path(params[:id]), class:'cours-file' do %>
        <i class="fas fa-file-download file-img mr-3"></i>
        <p><%= @cours.name %></p>
      <% end %>
    </div>
  <% end %>

  <% if @cours.aditional_files != [] %>
    <div class="bloc-cours">
      <h3>Fichiers supplémentaires : </h3>
      <div class="list-others-files">
        <% @cours.aditional_files.each do |file| %>
          <%= link_to cour_download_aditional_file_path(params[:id], file.identifier), class:'cours-file others-files' do %>
            <i class="fas fa-file-download file-img mr-3"></i>
            <%= file.identifier %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @cours.description != "" %>
    <div class="bloc-cours description">
      <h3>Informations : </h3>
      <div class="txt-info">
        <p><%= simple_format(@cours.description) %></p>
      </div>
    </div>
  <% end %>

  <% if current_user.status === "Admin" %>
    <div class="btn-cours">
      <%= link_to "Modifier", edit_cour_path(params[:id]), class:'btn mr-5' %>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete">
        Supprimer
      </button>
    </div>
  <% end %>
</div>

app/views/cours_users/authorization.html.erb
<div class="container">
  <div id="react-autho"></div>
</div>

<%= javascript_pack_tag 'authorization' %>

app/views/cours_users/index.html.erb
<div class="container">
  <div class="container">
  <div class="tab d-flex">
    <button class="tablinks histoire">Histoire</button>
    <button class="tablinks geo">Géographie</button>
    <button class="tablinks emc">EMC</button>
  </div>

  <div class="all-cours">
    <div id="Histoire" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">Histoire</h2>
      <% if !@hit_cours.empty? %>
          <% @hit_cours.each do |c| %>

            <%= link_to cour_path(c.id), class:'cours-link' do %>
              <div class="card-product">
                <img src="<%= c.img %>" />
                <div class="card-product-infos">
                  <h2><%= c.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
      <% else %>
        <p>Pas de cours d'histoire pour le moment</p>
      <% end %>
    </div>

    <div id="Géographie" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">Géographie</h2>
      <% if !@geo_cours.empty? %>
        <% @geo_cours.each do |c| %>
          <%= link_to cour_path(c.id), class:'cours-link' do %>
            <div class="card-product">
              <img src="<%= c.img %>" />
              <div class="card-product-infos">
                <h2><%= c.name %></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>Pas de cours de géographie pour le moment</p>
      <% end %>
    </div>

    <div id="EMC" class="tabcontent not-displayed rounded">
      <h2 class="title-cours">EMC</h2>
      <% if !@emc_cours.empty? %>
        <% @emc_cours.each do |c| %>
          <%= link_to cour_path(c.id), class:'cours-link' do %>
            <div class="card-product">
              <img src="<%= c.img %>" />
              <div class="card-product-infos">
                <h2><%= c.name %></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>Pas de cours d'EMC pour le moment</p>
      <% end %>
    </div>
  </div>
</div>

app/views/cours_users/new.html.erb
<div class="container">
  <h1 class="title-tab">Gestion des autorisations</h1>
  <div id="react-autho"></div>
</div>

<%= javascript_pack_tag 'authorization' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mes cours en ligne</title>

    <meta name="description" content="Retrouvez les cours d'histoire, géographie et d'EMC de Madame Olivia Lludriguez, avec un accès pour les professeurs et un accès pour ses élèves.">
    <%= favicon_link_tag %>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Martel:wght@400;800&display=swap" rel="stylesheet">

  </head>
  <body>
    <div id="contenu">
      <div id="main">
        <div class="div-flashes"><%= render 'shared/flashes' %></div>

        <% if user_signed_in? %>
          <%= render 'shared/navbar' %>
        <% end %>

        <%= yield %>
      </div>



      <% if user_signed_in? && current_user.status != "Elève" %>
        <%= render 'shared/footer' %>
      <% elsif !user_signed_in? %>
        <%= render 'shared/footer' %>
      <% end %>

    </div>


    <%= javascript_pack_tag 'application' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="bg-deconnected">
    <div class="en-tete">
      <% if !user_signed_in? %>
        <div class="btn-center">
          <a href="/"><%= image_tag('logo.png', class:'logo-disconnected') %></a>
        </div>
      <% end %>
      <h1 class="title-disconnected">Contact</h1>
    </div>
  <div class="container">
    <div class="container form-contact">
      <p>Si vous êtes professeur vous avez la possibilité de me contacter pour obtenir un accès à mes cours ou pour tout autre renseignement.</p>

      <form action="https://formspree.io/moqkakyb" method="POST">
        <div class="form-group">
          <label for="exampleFormControlInput1">Votre email:</label>
          <input type="email" class="form-control" id="exampleFormControlInput1" name="mail" placeholder="name@example.com" required>
        </div>

        <div class="form-group">
          <label for="exampleFormControlInput1">Votre nom:</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" name="nom" required>
        </div>

        <div class="form-group">
          <label for="exampleFormControlTextarea1">Votre message:</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="message"></textarea>
        </div>

        <div class="btn-center">
          <button type="submit" class="btn">Envoyer</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Pages#home</h1>
  <%= button_to "Se connecter", new_user_session_path, method: :get, class: "btn btn-secondary" %>
  <%= button_to "Contacter", contact_path, method: :get, class: "btn btn-secondary" %>
</div>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="general-div-footer row">
    <div class="d-flex col-sm">
      <p class="link-footer"><a href="<%= root_path %>">Accueil</a></p>
      <p><a href="<%= contact_path %>">Contact</a></p>
    </div>
    <div class="d-flex col-sm">
      <p class="link-footer">Site réalisé par <a href="http://lucasdubernard.com/" target="blank">Lucas Dubernard</a></p>
      <p>Copyright &copy; 2020 All Rights Reserved</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="<%= root_path %>"><%= image_tag('logo.png', class:'logo-nav') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user.status === 'Elève' %>
        <li class="nav-item">
            <%= link_to "Mes cours", cours_users_path, method: :get, class: "nav-link" %>
        </li>
      <% end %>
      <% if current_user.status === 'Admin' || current_user.status === 'Prof' %>
        <li class="nav-item">
          <%= link_to "Les cours", cours_path, method: :get, class: "nav-link" %>
        </li>
      <% end %>

      <% if current_user.status === 'Admin' %>
        <li class="nav-item">
          <%= link_to "Gestion des cours", new_cours_user_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Gestion des utilisateurs", users_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, method: :get, class: "nav-link" %>
        </li>
      <% end %>

      <li class="nav-item deconnexion">
          <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <h1 class="title-tab">Gestion des utilisateurs</h1>
  <ul class="list-group user-list">
    <% @users.each do |user| %>

  <!-- MODAL DELETE -->
      <div id="modal-<%= user.id %>" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="exampleModalLongTitle">Supprimer cet utilisateur ?</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Voulez vous vraiment supprimer cet utilisateur ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
              <%= button_to user_path(user), method: :delete, class:"btn btn-danger" do %>
                Supprimer
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <!-- MODAL DELET FINISH -->


      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex"><%= user.username %> (<%= user.status %>)</div>
        <% if user != current_user %>
          <span>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-<%= user.id %>">
              Supprimer
            </button>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="btn-center">
    <%= button_to "Créer un nouvel utilisateur", new_user_path, method: :get, class: "btn" %>
  </div>

</div>